Testing of github actions. Change lando version

diff --git a/.github/workflows/profile-install-test.yml b/.github/workflows/profile-install-test.yml
--- a/.github/workflows/profile-install-test.yml
+++ b/.github/workflows/profile-install-test.yml
@@ -7,12 +7,19 @@ jobs:
   Install-Lando-And-Test:
     runs-on: ubuntu-latest
     steps:
-      - name: Install Lando
+      - name: Grab latest edge Lando CLI
         run: |
-          curl -f#SL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.14.0/lando-x64-v3.14.0.deb; sudo dpkg -i --ignore-depends=docker-ce /tmp/lando.deb; rm -f /tmp/lando.deb;
+          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando-versions }}"
+          sudo chmod +x /usr/local/bin/lando    
+      - name: Move in lando config appropriate for testing
+        run: |
           mkdir -p ~/.lando/cache
           echo false > ~/.lando/cache/report_errors
           lando --clear
+      - name: Verify Lando works and we are dogfooding this plugin for tests
+        run: |
+          lando version
+          lando config --path plugins | grep php | grep /home/runner/work/php/php || (echo "::error:: Not dogfooding this plugin correctly! " && exit 1)
       - name: Cache Composer packages
         id: composer-cache
         uses: actions/cache@v3
